steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
    - 'app'
    - 'deploy'
    - 'server/app.yaml'
    - |
      [[ "$BRANCH_NAME" != "master"]] && --no-promote
      echo "Pushed to test"
timeout: "1600s"