steps:

- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'github.com/troyspencer/launch-wasm/game']
  env: ['PROJECT_ROOT=github.com/troyspencer/launch-wasm/game']

- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'github.com/troyspencer/launch-wasm/game']
  env: ['PROJECT_ROOT=github.com/troyspencer/launch-wasm/game']

- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']

- name: 'gcr.io/cloud-builders/yarn'
  id: 'build'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  waitFor: ['build']
  id: 'deploy'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      set -e
      if [[ "$BRANCH_NAME" == "master" ]]; then 
        gcloud app deploy server/app.yaml
      else 
        gcloud app deploy server/app.yaml --no-promote
      fi
      echo "Pushed to test"