steps:

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/image
  - --cache=true
  - --cache-ttl=6h

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      set -e
      if [[ "$BRANCH_NAME" == "master" ]]; then 
        gcloud app deploy server/app.yaml
      else 
        gcloud app deploy server/app.yaml --no-promote
      fi