steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      if [[ "$BRANCH_NAME" == "master" ]]; then 
        gcloud app deploy server/app.yaml
      else 
        gcloud app deploy server/app.yaml --no-promote
      fi
      echo "Pushed to test"
timeout: "1600s"