steps:

- name: 'gcr.io/cloud-builders/yarn'
  waitFor: ['-']
  id: 'installYarnDependencies'
  args: ['install']

- name: 'gcr.io/cloud-builders/yarn'
  waitFor: ['installYarnDependencies']
  id: 'buildApp'
  args: ['build']

- name: 'gcr.io/cloud-builders/gcloud'
  waitFor: ['buildApp']
  id: 'deployApp'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      set -e
      if [[ "$BRANCH_NAME" == "master" ]]; then 
        gcloud app deploy server/app.yaml
      else 
        gcloud app deploy server/app.yaml --no-promote
      fi