steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
    - '-c'
    - 'app'
    - 'deploy'
    - 'server/app.yaml'
    - |
      if [[ "$BRANCH_NAME" != "master"]]; then --no-promote
      fi
      echo "Pushed to test"
timeout: "1600s"