version: '3.7'
services:
  web:
    image: launch:latest
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: ./dist
        target: /go/src/github.com/troyspencer/launch/server/dist
    ports:
      - 8080:8080
volumes:
  server: